# UBC
## Programming in Python for DS

### Week 8

Instructor: Socorro Dominguez-Vidana

In [1]:
# Import libraries needed for this lab
import pandas as pd
import numpy as np

Overview

- [] Use **NumPy** to create **ndarrays** with `np.array()` and from functions such as `np.arange()`, `np.linspace()` and `np.ones()`.
- [] Describe the shape, dimension and size of an array.
- [] Identify null values in a dataframe and manage them by removing them using `.dropna()` or replacing them using `.fillna()`.
- [] Manipulate non-standard date/time formats into standard Pandas datetime using `pd.to_datetime()`.
- [] Find, and replace text from a dataframe using verbs such as `.replace()` and `.contains()`

### NumPy

$NumPy = Numerical Python (Extension)$

A NumPy array is like a container in Python that can hold a grid of numbers (or other data).
It facilitates doing math work.

In [2]:
data = {'col1': [1,2,3],
        'col1a': [2,3,5],
        'col2': ['a','b','c']}
df = pd.DataFrame(data)
df

col1  col1a col2
0     1      2    a
1     2      3    b
2     3      5    c

```python
for row in df.iterows():
   df.loc[row, 'col1'] + 3
```

In [4]:
df['col1'] + 3

0    4
1    5
2    6
Name: col1, dtype: int64

Creating:
- With `np.arange()`, you can create sequence arrays:

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

- With `np.linspace()`, you can create an array that generates evenly spaced values within a specified range:

In [8]:
np.linspace(0, 10, 12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [9]:
np.linspace((3, 1), 12, 3)

array([[ 3. ,  1. ],
       [ 7.5,  6.5],
       [12. , 12. ]])

In [10]:
pd.DataFrame(np.linspace((3, 1), 12, 3), columns = ['a', 'b'])

a     b
0   3.0   1.0
1   7.5   6.5
2  12.0  12.0

- With `np.ones()`, you can create an array filled with ones

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Knowing the **shape**, **dimension**, and **size** of an array helps us understand the structure and characteristics of the data stored in the array.

We can then decide which operations we can/should do.

In [14]:
my_list = [1,1,1]
my_list

[1, 1, 1]

In [15]:
my_list+3

TypeError: can only concatenate list (not "int") to list

In [16]:
[i + 3 for i in my_list]

[4, 4, 4]

In [17]:
array_ones = np.ones((2, 3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
array_ones+3

array([[4., 4., 4.],
       [4., 4., 4.]])

In [19]:
array_ones[1] = array_ones[1]+3
array_ones

array([[1., 1., 1.],
       [4., 4., 4.]])

More about np.arrays:  
https://realpython.com/numpy-scipy-pandas-correlation-python/  
https://realpython.com/numpy-array-programming/  

### Filling NAs

In [21]:
data = {'A': [1, 2, np.nan, 4],
        'B': [5, None, 7, 8],
        'C': [9, 10, 11, 12]}

df = pd.DataFrame(data)
df

A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  7.0  11
3  4.0  8.0  12

In [22]:
df['A'] + df['C']

0    10.0
1    12.0
2     NaN
3    16.0
dtype: float64

In [26]:
df_filled = df.fillna(0)
df_filled

A    B   C
0  1.0  5.0   9
1  2.0  0.0  10
2  0.0  7.0  11
3  4.0  8.0  12

Review the use of `.sum(axis = 1)`

In [ ]:
df_filled['A'] + df_filled['B'] + df_filled['C']

It might be tempting to do `fillna(0)` before applying that `+` but remember you can do this instead:

In [ ]:
df.sum(axis = 1)

### Droppping Rows

In [27]:
df

A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  7.0  11
3  4.0  8.0  12

In [28]:
df.dropna()

A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

In [29]:
df.dropna(subset='B')

A    B   C
0  1.0  5.0   9
2  NaN  7.0  11
3  4.0  8.0  12

In [32]:
df[~df['A'].isnull()]

A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
3  4.0  8.0  12

### DateTime Wrangling 

In [33]:
df = pd.read_csv('data/chopped.csv')
df.loc[1, 'air_date']

'January 20, 2009'

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   season            569 non-null    int64 
 1   season_episode    569 non-null    int64 
 2   series_episode    569 non-null    int64 
 3   episode_name      569 non-null    object
 4   episode_notes     456 non-null    object
 5   air_date          569 non-null    object
 6   judge1            568 non-null    object
 7   judge2            568 non-null    object
 8   judge3            568 non-null    object
 9   appetizer         569 non-null    object
 10  entree            569 non-null    object
 11  dessert           568 non-null    object
 12  contestant1       568 non-null    object
 13  contestant1_info  556 non-null    object
 14  contestant2       569 non-null    object
 15  contestant2_info  555 non-null    object
 16  contestant3       569 non-null    object
 17  contestant3_info

In [35]:
chopped = pd.read_csv('data/chopped.csv', parse_dates=["air_date"])
chopped.loc[1,'air_date']

Timestamp('2009-01-20 00:00:00')

In [37]:
chopped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   season            569 non-null    int64         
 1   season_episode    569 non-null    int64         
 2   series_episode    569 non-null    int64         
 3   episode_name      569 non-null    object        
 4   episode_notes     456 non-null    object        
 5   air_date          569 non-null    datetime64[ns]
 6   judge1            568 non-null    object        
 7   judge2            568 non-null    object        
 8   judge3            568 non-null    object        
 9   appetizer         569 non-null    object        
 10  entree            569 non-null    object        
 11  dessert           568 non-null    object        
 12  contestant1       568 non-null    object        
 13  contestant1_info  556 non-null    object        
 14  contestant2       569 non-

How can we look at the difference of dates?

In [39]:
chopped["air_date"].max()

Timestamp('2020-08-04 00:00:00')

In [40]:
my_diff = chopped["air_date"].max()-chopped["air_date"].min()
my_diff

Timedelta('4221 days 00:00:00')

In [43]:
type(my_diff.days)

int

In [49]:
(chopped["air_date"].max() - chopped["air_date"].min()).days

4221

Review [Documentation](https://pandas.pydata.org/pandas-docs/version/2.1/user_guide/timedeltas.html#attributes) to see different attributes.

How can I check the differences between dates in the whole data frame?

In [50]:
chopped["air_date"]

0     2009-01-13
1     2009-01-20
2     2009-01-27
3     2009-02-03
4     2009-02-10
         ...    
564   2020-06-23
565   2020-06-30
566   2020-07-07
567   2020-07-21
568   2020-07-28
Name: air_date, Length: 569, dtype: datetime64[ns]

In [55]:
chopped['air_date'].dt.month_name()

0       January
1       January
2       January
3      February
4      February
         ...   
564        June
565        June
566        July
567        July
568        July
Name: air_date, Length: 569, dtype: object

In [59]:
chopped["air_date"].diff()
# Notice the first NaT

0         NaT
1      7 days
2      7 days
3      7 days
4      7 days
        ...  
564    7 days
565    7 days
566    7 days
567   14 days
568    7 days
Name: air_date, Length: 569, dtype: timedelta64[ns]

### Replacing Strings in Data Frame

In [60]:
data = {'A': ["Africa", "  Asia", "America", "Asia"],
        'B': [5, np.nan, 7, 8],
        'C': ['$9', '$10', '$11', '$12']}

df = pd.DataFrame(data)
df

A    B    C
0   Africa  5.0   $9
1     Asia  NaN  $10
2  America  7.0  $11
3     Asia  8.0  $12

In [ ]:
df['B'] + df['C']

In [61]:
df['A'].value_counts()

A
Africa     1
  Asia     1
America    1
Asia       1
Name: count, dtype: int64

In [62]:
df['A'].str.strip().value_counts()

A
Asia       2
Africa     1
America    1
Name: count, dtype: int64

In [63]:
"hello".replace("e", "a")

'hallo'

In [64]:
df['A'].str.replace('  Asia', 'Asia').value_counts()

A
Asia       2
Africa     1
America    1
Name: count, dtype: int64

In [67]:
df['A'].value_counts()

A
Africa     1
  Asia     1
America    1
Asia       1
Name: count, dtype: int64

In [68]:
df['A'].str.replace('a', 'b')

0     Africb
1       Asib
2    Americb
3       Asib
Name: A, dtype: object

In [ ]:
sentence = "hello"
sentence

In [ ]:
sentence.replace('e', 'a')

In [69]:
df[df['A'].str.contains('Am')]

A    B    C
2  America  7.0  $11

In [70]:
df[df['A'].str.contains('Am')] = 'B'

In [71]:
df

A    B    C
0  Africa  5.0   $9
1    Asia  NaN  $10
2       B    B    B
3    Asia  8.0  $12

#### Assignment Question 3: Cleaning the dirty data frame

In [ ]:
#clean.copy()

In [72]:
dirty = pd.read_csv('data/dirty_gapminder.csv')
dirty.head(2)

year        pop  lifeExp   gdpPercap continent      country
0  1952  8425333.0   28.801  779.445314      Asia  Afghanistan
1  1957  9240934.0   30.332  820.853030      Asia  Afghanistan

In [73]:
clean = pd.read_csv('data/clean_gapminder.csv')
clean.head(2)

country  year        pop continent  lifeExp   gdpPercap
0  Afghanistan  1952  8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957  9240934.0      Asia   30.332  820.853030

Motivation: Make dirty look the same way as clean

In [75]:
dirty[(~clean.eq(dirty)).any(axis=1)]#.shape

year           pop   lifeExp     gdpPercap continent   
240  1952  1.478558e+07  68.75000  11367.161120       NaN  \
241  1957  1.701015e+07  69.96000  12489.950060       NaN   
242  1962  1.898585e+07  71.30000  13462.485550       NaN   
243  1967  2.081977e+07  72.13000  16076.588030       NaN   
244  1972  2.228450e+07  72.88000  18970.570860       NaN   
245  1977  2.379640e+07  74.21000  22090.883060       NaN   
246  1982  2.520190e+07  75.76000  22898.792140       NaN   
247  1987  2.654970e+07  76.86000  26626.515030       NaN   
248  1992  2.852350e+07  77.95000  26342.884260       NaN   
249  1997  3.030584e+07  78.61000  28954.925890       NaN   
250  2002  3.190227e+07  79.77000  33328.965070       NaN   
251  2007  3.339014e+07  80.65300  36319.235010       NaN   
257  1977  2.167533e+06  46.77500   1109.374338    Africa   
258  1982  2.476971e+06  48.29500    956.752991    Africa   
259  1987  2.840009e+06  50.48500    844.876350    Africa   
260  1992  3.265124e+06  49.39600    747.905525    Africa   
293  1977  9.434550e+08  63.96736    741.237470      Asia   
294  1982  1.000281e+09  65.52500    962.421381      Asia   
295  1987  1.084035e+09  67.27400   1378.904018      Asia   
296  1992  1.164970e+09  68.69000   1655.784158      Asia   
302  1962  1.700988e+07  57.86300   2492.351109  Americas   
303  1967  1.976403e+07  59.96300   2678.729839  Americas   
328  1972  2.300767e+07  45.98900    904.896068    Africa   
333  1997  4.779899e+07  42.58700    312.188423    Africa   
369  1997  1.462597e+07  47.99100   1786.265407    Africa   
815  2007  6.053193e+06  72.53500   4519.461171      Asia   
828  1952  8.865488e+06  50.05600   1088.277758      Asia   
829  1957  9.411381e+06  54.08100   1571.134655      Asia   

                              country  
240                            Canada  
241                            Canada  
242                            Canada  
243                            Canada  
244                            Canada  
245                            Canada  
246                            Canada  
247                            Canada  
248                            Canada  
249                            Canada  
250                            Canada  
251                            Canada  
257          Central african republic  
258          Central african republic  
259          Central african republic  
260          Central african republic  
293                             china  
294                             china  
295                             china  
296                             china  
302                      Colombia      
303                      Colombia      
328  Democratic Republic of the Congo  
333        Congo, Democratic Republic  
369                      Cote d'Ivore  
815                            Jordan  
828                  Korea, Dem. Rep.  
829                  Korea, Dem. Rep.

Breaking the code into parts

In [80]:
clean[(~clean.eq(dirty)).any(axis=1)]

country  year           pop continent   lifeExp   
240                    Canada  1952  1.478558e+07  Americas  68.75000  \
241                    Canada  1957  1.701015e+07  Americas  69.96000   
242                    Canada  1962  1.898585e+07  Americas  71.30000   
243                    Canada  1967  2.081977e+07  Americas  72.13000   
244                    Canada  1972  2.228450e+07  Americas  72.88000   
245                    Canada  1977  2.379640e+07  Americas  74.21000   
246                    Canada  1982  2.520190e+07  Americas  75.76000   
247                    Canada  1987  2.654970e+07  Americas  76.86000   
248                    Canada  1992  2.852350e+07  Americas  77.95000   
249                    Canada  1997  3.030584e+07  Americas  78.61000   
250                    Canada  2002  3.190227e+07  Americas  79.77000   
251                    Canada  2007  3.339014e+07  Americas  80.65300   
257  Central African Republic  1977  2.167533e+06    Africa  46.77500   
258  Central African Republic  1982  2.476971e+06    Africa  48.29500   
259  Central African Republic  1987  2.840009e+06    Africa  50.48500   
260  Central African Republic  1992  3.265124e+06    Africa  49.39600   
293                     China  1977  9.434550e+08      Asia  63.96736   
294                     China  1982  1.000281e+09      Asia  65.52500   
295                     China  1987  1.084035e+09      Asia  67.27400   
296                     China  1992  1.164970e+09      Asia  68.69000   
302                  Colombia  1962  1.700988e+07  Americas  57.86300   
303                  Colombia  1967  1.976403e+07  Americas  59.96300   
328          Congo, Dem. Rep.  1972  2.300767e+07    Africa  45.98900   
333          Congo, Dem. Rep.  1997  4.779899e+07    Africa  42.58700   
369             Cote d'Ivoire  1997  1.462597e+07    Africa  47.99100   
815                    Jordan  2007  6.053193e+06      Asia  72.53500   
828          Korea, Dem. Rep.  1952  8.865488e+06      Asia  50.05600   
829          Korea, Dem. Rep.  1957  9.411381e+06      Asia  54.08100   

        gdpPercap  
240  11367.161120  
241  12489.950060  
242  13462.485550  
243  16076.588030  
244  18970.570860  
245  22090.883060  
246  22898.792140  
247  26626.515030  
248  26342.884260  
249  28954.925890  
250  33328.965070  
251  36319.235010  
257   1109.374338  
258    956.752991  
259    844.876350  
260    747.905525  
293    741.237470  
294    962.421381  
295   1378.904018  
296   1655.784158  
302   2492.351109  
303   2678.729839  
328    904.896068  
333    312.188423  
369   1786.265407  
815   4519.461171  
828   1088.277758  
829   1571.134655

In [ ]:
dirty[(~clean.eq(dirty)).any(axis=1)]

In [81]:
dirty['continent'].value_counts()

continent
Africa      624
Asia        393
Europe      360
Americas    288
Oceania      24
    Asia      3
Name: count, dtype: int64

In [ ]:
# This is the goal
clean[(~clean.eq(dirty)).any(axis=1)]

```python
dirty['country'].str.replace('china', 'China')
### str.strip() <- country and continent
```

```python
def data_cleaner(dirty_df):
    clean_df['country'] = dirty_df['country'].str.replace('china', 'China')
    clean_df['continent'] = clean_df['continent'].str.split()
    return clean_df

cleaned_data = data_cleaner(dirty)
```
```python
cleaned_data[(~clean.eq(cleaned_data)).any(axis=1)]
```
```python
t.test_
```

```python
def data_cleaner(dirty):
    steps 1
    steps 2
    steps 3
    return cleaned_data
```

```python
new_data = data_cleaner(dirty_df)
```
```python
clean[(~clean.eq(new_data)).any(axis=1)]
```

In [ ]:
##On Wednesday

In [ ]:
(dirty = dirty[dirty.isnull().any(axis=1)])

In [ ]:
def cleaned_gapminder(dirty_df):
    
    # Let's fill the na's with `.fillna()`
    dirty_df = dirty_df.fillna(value="Americas")
    dirty_df.columns = ['country', 'year', 'pop', 'continent', 'lifeExp', 'gdpPercap']

    return dirty_df

In [ ]:
cleaned_data = cleaned_gapminder(dirty)

In [ ]:
clean[(~cleaned_data.eq(clean)).any(axis=1)].head(2)

In [ ]:
clean.columns

In [ ]:
cleaned_data[(~cleaned_data.eq(clean)).any(axis=1)].head(2)